services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_DB: ticketing_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: E.mFeg8ohLV!4!vjct8hyE.rt_m8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    command: bash -c "chmod +x entrypoint.sh && ./entrypoint.sh"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:E.mFeg8ohLV!4!vjct8hyE.rt_m8@db:5432/ticketing_db

volumes:
  postgres_data: