# Generated by Django 5.0.1 on 2025-09-13 10:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('phone_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('site_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('ticket_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ticket_subject', models.CharField(choices=[('self_location', 'Self Location'), ('registered_address', 'Registered Address')], max_length=50)),
                ('structured_response', models.JSONField(blank=True, null=True)),
                ('original_free_text', models.TextField(blank=True, null=True)),
                ('openai_summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('High Priority', 'High Priority'), ('Medium Priority', 'Medium Priority'), ('Info', 'Info')], max_length=20)),
                ('location_source', models.CharField(choices=[('shared_location', 'Shared Location'), ('from_customers_table', 'From Customers Table')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_alert_sent', models.BooleanField(default=False)),
                ('is_primary_report', models.BooleanField(default=True)),
                ('reporting_phone', models.ForeignKey(db_column='reporting_phone', on_delete=django.db.models.deletion.CASCADE, to='tickets.customer')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
