# Generated by Django 5.0.1 on 2025-09-13 11:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_alert_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_primary_report',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='location_source',
            field=models.CharField(blank=True, choices=[('shared_location', 'Shared Location'), ('from_customers_table', 'From Customers Table')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reporting_phone',
            field=models.ForeignKey(blank=True, db_column='reporting_phone', null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.customer'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('High Priority', 'High Priority'), ('Medium Priority', 'Medium Priority'), ('Info', 'Info')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_subject',
            field=models.CharField(blank=True, choices=[('self_location', 'Self Location'), ('registered_address', 'Registered Address')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
