# Generated by Django 5.0.1 on 2025-09-13 11:54

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_customer_full_name_alter_ticket_is_alert_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='is_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='is_primary_report',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 13, 11, 54, 2, 805366, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
