# Generated by Django 5.0.1 on 2025-09-14 17:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_add_database_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
